// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 takes the seed command here rather than from package.json.
    // Node 24 strips types natively, so this needs no ts-node or tsx.
    seed: "node scripts/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
